nombre = input("Ingresa tu nombre: ")
apellido = input("Ingresa tu apellido: ")
codigo_seccion = input("Ingresa tu código de sección: ")
sede = input("Ingresa tu sede: ")

print("La información ingresada es la siguiente:")
print("Nombre: " + nombre)
print("Apellido: " + apellido)
print("Código de sección: " + codigo_seccion)
print("Sede: " + sede)
